spring.application.name=sistema_tevcol

# 🔴 CAMBIA ESTA LÍNEA - prueba con "MySQL" (con M mayúscula)
spring.datasource.url=jdbc:mysql://mysql:${MYSQLPORT}/${MYSQLDATABASE}
# O prueba con mysql.railway.internal:
# spring.datasource.url=jdbc:mysql://mysql.railway.internal:${MYSQLPORT}/${MYSQLDATABASE}

spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ✅ Configuración JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

server.port=${PORT:8080}

# Configuración de correo
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=eddy.lucero1553@utc.edu.ec
spring.mail.password=buhn snje ircx evcv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true