spring.application.name=sistema_tevcol

# NO modifiques estas variables, Railway las llenará solo
spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Dialecto actualizado para MySQL 9 (el que tienes en Railway)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Configuración de puerto para Railway
server.port=${PORT:8080}

# Tu configuración de correo (esto se queda igual)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=eddy.lucero1553@utc.edu.ec
spring.mail.password=buhn snje ircx evcv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true